name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate Salesforce Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias DevOrg

      - name: Debug – current directory
        run: pwd

      - name: Debug – list root files
        run: ls -la

      - name: Debug – check force-app
        run: ls -la force-app

      - name: Deploy to Salesforce
        run: sf project deploy start --manifest manifest/package.xml --target-org DevOrg --ignore-warnings
        
